const TREASURY_DATA = {
  "annees": [
    2026,
    2025
  ],
  "adherents": {
    "2025": [
      {
        "nom": "PREVOT",
        "prenom": "ALEXANDRE",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 292,
        "totalDu": 145,
        "resteAPayer": -147,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "alex.prevot1@laposte.net"
      },
      {
        "nom": "Membre conf.",
        "prenom": "",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pdemarsy@gmail.com"
      },
      {
        "nom": "LARIVIERE",
        "prenom": "GERALD",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "gege.kristel@free.fr"
      },
      {
        "nom": "LANGLET",
        "prenom": "FREDERIC",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL1"
        ],
        "email": "kinane.poc@hotmail.fr"
      },
      {
        "nom": "FONTAINE",
        "prenom": "JEAN BERNARD",
        "college": "",
        "modePaiement": "Chèque",
        "dateEntree": "2024-04-08",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jb.fontaine68@gmail.com"
      },
      {
        "nom": "DELPLACE",
        "prenom": "DAVID",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 221,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "Complément en 2025",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "daviddelplace62@gmail.com"
      },
      {
        "nom": "BOBER",
        "prenom": "DEBORAH",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2024-05-21",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "deborahbober1@gmail.com"
      },
      {
        "nom": "LECADIEU",
        "prenom": "LUCIE",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "1905-07-15",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "lucie.ecadieu@gmail.com"
      },
      {
        "nom": "ROUSSIN",
        "prenom": "GWENDOLINE",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 152,
        "totalDu": 145,
        "resteAPayer": -7,
        "commentaire": "// Rémy",
        "postesFO": [],
        "postesCSE": [
          "TIT COL3"
        ],
        "email": "gwendolineroussin@gmail.com"
      },
      {
        "nom": "LEMOINE",
        "prenom": "MARC-ANTOINE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-04-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lemoine.marc.antoine.fo@gmail.com"
      },
      {
        "nom": "KLAWITTER",
        "prenom": "JULIE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "TIT COL1"
        ],
        "email": "blancard80@hotmail.com"
      },
      {
        "nom": "BEGUIN",
        "prenom": "ALLAN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-01-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 175,
        "totalDu": 145,
        "resteAPayer": -30,
        "commentaire": "Attente reçu 175€ (2024 payé en 2025)",
        "postesFO": [],
        "postesCSE": [
          "SUP COL1"
        ],
        "email": "allan.bgn80@outlook.fr"
      },
      {
        "nom": "BONARD",
        "prenom": "PASCAL",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2024-04-05",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 103.5,
        "totalDu": 145,
        "resteAPayer": 41.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fredben.bonard@hotmail.fr"
      },
      {
        "nom": "TELLIER",
        "prenom": "FABRICE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabricetellier7@gmail.com"
      },
      {
        "nom": "Membre conf.",
        "prenom": "LAURENT",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 91,
        "totalDu": 145,
        "resteAPayer": 54,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "caumartinlaurent@gmail.com"
      },
      {
        "nom": "RIVILLON",
        "prenom": "LUCIE",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2023-01-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1
        ],
        "totalRecu": 34.5,
        "totalDu": 145,
        "resteAPayer": 110.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lucie.rivillon@outlook.fr"
      },
      {
        "nom": "SALVA",
        "prenom": "NATHALIE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2023-05-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "TIT COL2"
        ],
        "email": "nathalie.salva@free.fr"
      },
      {
        "nom": "MAQUET",
        "prenom": "SEBASTIEN",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "seb.mqt@icloud.com"
      },
      {
        "nom": "COLAUX",
        "prenom": "PAUL HENRY",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "chticard.phc@gmail.com"
      },
      {
        "nom": "LEGRAS",
        "prenom": "JEREMY",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "Mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "jeremyleg2@outlook.fr"
      },
      {
        "nom": "DECROIX",
        "prenom": "PATRICE",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "1 mois offert 2024 (trop perçu 2023)",
        "postesFO": [],
        "postesCSE": [],
        "email": "decroix.patrice3@gmail.com"
      },
      {
        "nom": "CLOLERY",
        "prenom": "MARC",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "louis.clolery@orange.fr"
      },
      {
        "nom": "DHENIN",
        "prenom": "LUCIEN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-05-03",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lucien80080@hotmail.fr"
      },
      {
        "nom": "CARPENTIER",
        "prenom": "THOMAS",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-02-10",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "carpentierthomas27@yahoo.fr"
      },
      {
        "nom": "VAILLANT",
        "prenom": "MICKAEL",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "mvaillant0106@gmail.com"
      },
      {
        "nom": "DEMACHY",
        "prenom": "AURORE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        "totalRecu": 91.5,
        "totalDu": 145,
        "resteAPayer": 53.5,
        "commentaire": "SMS le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "aurore.demachy@hotmail.fr"
      },
      {
        "nom": "MARCOTTE",
        "prenom": "DYLAN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 134.5,
        "totalDu": 145,
        "resteAPayer": 10.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dylan.marcotte27@gmail.com"
      },
      {
        "nom": "DIEUDONNE",
        "prenom": "Isabelle",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-19",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "isadieudonne80@icloud.com"
      },
      {
        "nom": "FERNANDES",
        "prenom": "DAVID",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "david.fds47@gmail.com"
      },
      {
        "nom": "PRINGARBE",
        "prenom": "SEBASTIEN",
        "college": 2,
        "modePaiement": "Paypall",
        "dateEntree": "2023-01-20",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "A éclaircir mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "seb-p.msn@hotmail.fr"
      },
      {
        "nom": "BRUVIER",
        "prenom": "Ludovic",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-19",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "Ludovic.bruvier@valeo.com"
      },
      {
        "nom": "PECOURT",
        "prenom": "ALINE",
        "college": 1,
        "modePaiement": "",
        "dateEntree": "2024-03-20",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 11.5,
        "totalDu": 145,
        "resteAPayer": 133.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "aline.blin15@yahoo.fr"
      },
      {
        "nom": "RAY",
        "prenom": "MARC",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 76,
        "totalDu": 145,
        "resteAPayer": 69,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "mafrray@gmail.com"
      },
      {
        "nom": "SAKPONOU",
        "prenom": "CONSTANT",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "consty1999@yahoo.fr"
      },
      {
        "nom": "RAY",
        "prenom": "GUILLAUME",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "guillaumeray13@gmail.com"
      },
      {
        "nom": "LECONTE",
        "prenom": "CYRIL",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "cyril.leconte80000@gmail.com"
      },
      {
        "nom": "DERCOURT",
        "prenom": "PHILIPPE",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL2"
        ],
        "email": "philippedercourt@orange.fr"
      },
      {
        "nom": "DOGMONT",
        "prenom": "MARIO",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dogmontmario@gmail.com"
      },
      {
        "nom": "BEAUCOURT",
        "prenom": "HERVE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "herve.beaucourt@orange.fr"
      },
      {
        "nom": "TEIXEIRA",
        "prenom": "OLIVIER",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2023-09-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "olivier.teixeira@valeo.com"
      },
      {
        "nom": "SAUVE",
        "prenom": "JEREMIE",
        "college": "",
        "modePaiement": "Virement",
        "dateEntree": "2025-06-26",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 64,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jeremie.sauve@hotmail.fr"
      },
      {
        "nom": "PORET",
        "prenom": "AURELIEN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-08-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0
        ],
        "totalRecu": 120,
        "totalDu": 145,
        "resteAPayer": 25,
        "commentaire": "Virement à faire le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "aureliennn@hotmail.fr"
      },
      {
        "nom": "MOREL",
        "prenom": "FRANCOIS",
        "college": 1,
        "modePaiement": "Paypall",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "Mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "francois.morel710@gmail.com"
      },
      {
        "nom": "BEAUGEOIS",
        "prenom": "ANTHONY",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 80.5,
        "totalDu": 145,
        "resteAPayer": 64.5,
        "commentaire": "Message vocal 13/01",
        "postesFO": [],
        "postesCSE": [
          "TIT COL1"
        ],
        "email": "beaugeoisanthony@hotmail.fr"
      },
      {
        "nom": "BACHA",
        "prenom": "KARIM",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0
        ],
        "totalRecu": 115,
        "totalDu": 145,
        "resteAPayer": 30,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "bachakarim80260@gmail.com"
      },
      {
        "nom": "VAAST",
        "prenom": "FABRICE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-09-09",
        "actif": false,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 123.5,
        "totalDu": 145,
        "resteAPayer": 21.5,
        "commentaire": "SMS le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabrice.vaast@gmail.com"
      },
      {
        "nom": "PORTAUX",
        "prenom": "REMY",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "// Gwen",
        "postesFO": [],
        "postesCSE": [],
        "email": "remy.portaux@valeo.com"
      },
      {
        "nom": "AMET",
        "prenom": "Benoit",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "amet.benoit@gmail.com"
      },
      {
        "nom": "LUCET",
        "prenom": "DAVID",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "david.lucet.fom@gmail.com"
      },
      {
        "nom": "FOLLAIN",
        "prenom": "FRANCK",
        "college": 2,
        "modePaiement": "",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "franck.follain@wanadoo.fr"
      },
      {
        "nom": "LOURDEL",
        "prenom": "BENOIT",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2024-09-04",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "DON 2024 50cts",
        "postesFO": [],
        "postesCSE": [],
        "email": "b.lourdel@orange.fr"
      },
      {
        "nom": "DEGOUY",
        "prenom": "Audrie",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "audriedegouy@orange.fr"
      },
      {
        "nom": "LENNE",
        "prenom": "Jean-Luc",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jean-luc.lenne@wanadoo.fr"
      },
      {
        "nom": "RASET",
        "prenom": "David",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-01-17",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "adel.gab@orange.fr"
      },
      {
        "nom": "BULANT",
        "prenom": "Fabrice",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-01-17",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabrice.bulant@outlook.com"
      },
      {
        "nom": "VALOUR",
        "prenom": "Anthony",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-02-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "thony1991@gmail.com"
      },
      {
        "nom": "DEBUIGNY",
        "prenom": "ELISABETH",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-02-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "elisabethdebuigny@yahoo.com"
      },
      {
        "nom": "DAVID",
        "prenom": "DUMEIGE",
        "college": "",
        "modePaiement": "",
        "dateEntree": "",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dd.dumeige@laposte.net"
      },
      {
        "nom": "SOUILLARD",
        "prenom": "MICKAEL",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-01-01",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "micka.80@live.fr"
      },
      {
        "nom": "DUPONT",
        "prenom": "VINCENT",
        "college": 1,
        "modePaiement": "",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-07-01",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dupont.vincent12@aliceadsl.fr"
      },
      {
        "nom": "DEVAUX",
        "prenom": "FREDERIC",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-03-06",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 23,
        "totalDu": 145,
        "resteAPayer": 122,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "wazoo.80@hotmail.fr"
      },
      {
        "nom": "TRAVERS",
        "prenom": "JEAN-LUC",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 41.5,
        "totalDu": 145,
        "resteAPayer": 103.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jl.travers@laposte.net"
      },
      {
        "nom": "BOUYSSOU",
        "prenom": "PHILIPPE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2025-01-22",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 41.5,
        "totalDu": 0,
        "resteAPayer": -41.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "philippe.bouyssou2@orange.fr"
      },
      {
        "nom": "Membre conf.",
        "prenom": "",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "2024-10-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 76,
        "totalDu": 145,
        "resteAPayer": 69,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pdemarsy@gmail.com"
      },
      {
        "nom": "PAUCHET",
        "prenom": "CEDRIC",
        "college": "",
        "modePaiement": "Virement",
        "dateEntree": "2024-03-05",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pauchetcedric@gmail.com"
      },
      {
        "nom": "CROISY",
        "prenom": "GINO",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "+ MM",
        "postesFO": [],
        "postesCSE": [
          "TIT COL2"
        ],
        "email": "gino.croisy@gmail.com"
      }
    ],
    "2026": [
      {
        "nom": "Membre conf.",
        "prenom": "",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pdemarsy@gmail.com"
      },
      {
        "nom": "LECADIEU",
        "prenom": "LUCIE",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "1905-07-15",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "lucie.ecadieu@gmail.com"
      },
      {
        "nom": "DIEUDONNE",
        "prenom": "Isabelle",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-19",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "isadieudonne80@icloud.com"
      },
      {
        "nom": "FERNANDES",
        "prenom": "DAVID",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "david.fds47@gmail.com"
      },
      {
        "nom": "PRINGARBE",
        "prenom": "SEBASTIEN",
        "college": 2,
        "modePaiement": "Paypall",
        "dateEntree": "2023-01-20",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "A éclaircir mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "seb-p.msn@hotmail.fr"
      },
      {
        "nom": "BRUVIER",
        "prenom": "Ludovic",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-19",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "Ludovic.bruvier@valeo.com"
      },
      {
        "nom": "PECOURT",
        "prenom": "ALINE",
        "college": 1,
        "modePaiement": "",
        "dateEntree": "2024-03-20",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 11.5,
        "totalDu": 145,
        "resteAPayer": 133.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "aline.blin15@yahoo.fr"
      },
      {
        "nom": "RAY",
        "prenom": "MARC",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 76,
        "totalDu": 145,
        "resteAPayer": 69,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "mafrray@gmail.com"
      },
      {
        "nom": "BEAUGEOIS",
        "prenom": "ANTHONY",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 80.5,
        "totalDu": 145,
        "resteAPayer": 64.5,
        "commentaire": "Message vocal 13/01",
        "postesFO": [],
        "postesCSE": [
          "TIT COL1"
        ],
        "email": "beaugeoisanthony@hotmail.fr"
      },
      {
        "nom": "BACHA",
        "prenom": "KARIM",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0
        ],
        "totalRecu": 115,
        "totalDu": 145,
        "resteAPayer": 30,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "bachakarim80260@gmail.com"
      },
      {
        "nom": "VAAST",
        "prenom": "FABRICE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-09-09",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 123.5,
        "totalDu": 145,
        "resteAPayer": 21.5,
        "commentaire": "SMS le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabrice.vaast@gmail.com"
      },
      {
        "nom": "AMET",
        "prenom": "Benoit",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "amet.benoit@gmail.com"
      },
      {
        "nom": "LUCET",
        "prenom": "DAVID",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "david.lucet.fom@gmail.com"
      },
      {
        "nom": "FOLLAIN",
        "prenom": "FRANCK",
        "college": 2,
        "modePaiement": "",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "franck.follain@wanadoo.fr"
      },
      {
        "nom": "LOURDEL",
        "prenom": "BENOIT",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2024-09-04",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "DON 2024 50cts",
        "postesFO": [],
        "postesCSE": [],
        "email": "b.lourdel@orange.fr"
      },
      {
        "nom": "DEGOUY",
        "prenom": "Audrie",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "audriedegouy@orange.fr"
      },
      {
        "nom": "LENNE",
        "prenom": "Jean-Luc",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2024-12-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jean-luc.lenne@wanadoo.fr"
      },
      {
        "nom": "RASET",
        "prenom": "David",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-01-17",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "adel.gab@orange.fr"
      },
      {
        "nom": "BULANT",
        "prenom": "Fabrice",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-01-17",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabrice.bulant@outlook.com"
      },
      {
        "nom": "VALOUR",
        "prenom": "Anthony",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-02-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "thony1991@gmail.com"
      },
      {
        "nom": "DEBUIGNY",
        "prenom": "ELISABETH",
        "college": "",
        "modePaiement": "",
        "dateEntree": "2025-02-06",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "elisabethdebuigny@yahoo.com"
      },
      {
        "nom": "DAVID",
        "prenom": "DUMEIGE",
        "college": "",
        "modePaiement": "",
        "dateEntree": "",
        "dateSortie": "1905-07-17",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dd.dumeige@laposte.net"
      },
      {
        "nom": "SOUILLARD",
        "prenom": "MICKAEL",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-01-01",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "micka.80@live.fr"
      },
      {
        "nom": "DUPONT",
        "prenom": "VINCENT",
        "college": 1,
        "modePaiement": "",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-07-01",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dupont.vincent12@aliceadsl.fr"
      },
      {
        "nom": "DEVAUX",
        "prenom": "FREDERIC",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "2025-03-06",
        "actif": false,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 23,
        "totalDu": 145,
        "resteAPayer": 122,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "wazoo.80@hotmail.fr"
      },
      {
        "nom": "TRAVERS",
        "prenom": "JEAN-LUC",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 41.5,
        "totalDu": 145,
        "resteAPayer": 103.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jl.travers@laposte.net"
      },
      {
        "nom": "BOUYSSOU",
        "prenom": "PHILIPPE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2025-01-22",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 41.5,
        "totalDu": 0,
        "resteAPayer": -41.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "philippe.bouyssou2@orange.fr"
      },
      {
        "nom": "Membre conf.",
        "prenom": "",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "2024-10-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 76,
        "totalDu": 145,
        "resteAPayer": 69,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pdemarsy@gmail.com"
      },
      {
        "nom": "PAUCHET",
        "prenom": "CEDRIC",
        "college": "",
        "modePaiement": "Virement",
        "dateEntree": "2024-03-05",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "pauchetcedric@gmail.com"
      },
      {
        "nom": "CROISY",
        "prenom": "GINO",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "NON",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "+ MM",
        "postesFO": [],
        "postesCSE": [
          "TIT COL2"
        ],
        "email": "gino.croisy@gmail.com"
      },
      {
        "nom": "PREVOT",
        "prenom": "ALEXANDRE",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 292,
        "totalDu": 145,
        "resteAPayer": -147,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "alex.prevot1@laposte.net"
      },
      {
        "nom": "LARIVIERE",
        "prenom": "GERALD",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "gege.kristel@free.fr"
      },
      {
        "nom": "LANGLET",
        "prenom": "FREDERIC",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL1"
        ],
        "email": "kinane.poc@hotmail.fr"
      },
      {
        "nom": "FONTAINE",
        "prenom": "JEAN BERNARD",
        "college": "",
        "modePaiement": "Chèque",
        "dateEntree": "2024-04-08",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jb.fontaine68@gmail.com"
      },
      {
        "nom": "DELPLACE",
        "prenom": "DAVID",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 221,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "Complément en 2025",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "daviddelplace62@gmail.com"
      },
      {
        "nom": "BOBER",
        "prenom": "DEBORAH",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2024-05-21",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "deborahbober1@gmail.com"
      },
      {
        "nom": "ROUSSIN",
        "prenom": "GWENDOLINE",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 152,
        "totalDu": 145,
        "resteAPayer": -7,
        "commentaire": "// Rémy",
        "postesFO": [],
        "postesCSE": [
          "TIT COL3"
        ],
        "email": "gwendolineroussin@gmail.com"
      },
      {
        "nom": "LEMOINE",
        "prenom": "MARC-ANTOINE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-04-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lemoine.marc.antoine.fo@gmail.com"
      },
      {
        "nom": "KLAWITTER",
        "prenom": "JULIE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "TIT COL1"
        ],
        "email": "blancard80@hotmail.com"
      },
      {
        "nom": "BEGUIN",
        "prenom": "ALLAN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-01-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 175,
        "totalDu": 145,
        "resteAPayer": -30,
        "commentaire": "Attente reçu 175€ (2024 payé en 2025)",
        "postesFO": [],
        "postesCSE": [
          "SUP COL1"
        ],
        "email": "allan.bgn80@outlook.fr"
      },
      {
        "nom": "BONARD",
        "prenom": "PASCAL",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2024-04-05",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 103.5,
        "totalDu": 145,
        "resteAPayer": 41.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fredben.bonard@hotmail.fr"
      },
      {
        "nom": "TELLIER",
        "prenom": "FABRICE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "fabricetellier7@gmail.com"
      },
      {
        "nom": "Membre conf.",
        "prenom": "LAURENT",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 91,
        "totalDu": 145,
        "resteAPayer": 54,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "caumartinlaurent@gmail.com"
      },
      {
        "nom": "RIVILLON",
        "prenom": "LUCIE",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "2023-01-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "TEMPO",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1
        ],
        "totalRecu": 34.5,
        "totalDu": 145,
        "resteAPayer": 110.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lucie.rivillon@outlook.fr"
      },
      {
        "nom": "SALVA",
        "prenom": "NATHALIE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2023-05-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "TIT COL2"
        ],
        "email": "nathalie.salva@free.fr"
      },
      {
        "nom": "MAQUET",
        "prenom": "SEBASTIEN",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "seb.mqt@icloud.com"
      },
      {
        "nom": "COLAUX",
        "prenom": "PAUL HENRY",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL3"
        ],
        "email": "chticard.phc@gmail.com"
      },
      {
        "nom": "LEGRAS",
        "prenom": "JEREMY",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "Mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "jeremyleg2@outlook.fr"
      },
      {
        "nom": "DECROIX",
        "prenom": "PATRICE",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "1 mois offert 2024 (trop perçu 2023)",
        "postesFO": [],
        "postesCSE": [],
        "email": "decroix.patrice3@gmail.com"
      },
      {
        "nom": "CLOLERY",
        "prenom": "MARC",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "louis.clolery@orange.fr"
      },
      {
        "nom": "DHENIN",
        "prenom": "LUCIEN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-05-03",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lucien80080@hotmail.fr"
      },
      {
        "nom": "CARPENTIER",
        "prenom": "THOMAS",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-02-10",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "carpentierthomas27@yahoo.fr"
      },
      {
        "nom": "VAILLANT",
        "prenom": "MICKAEL",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "mvaillant0106@gmail.com"
      },
      {
        "nom": "DEMACHY",
        "prenom": "AURORE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "TEMPO",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1
        ],
        "totalRecu": 91.5,
        "totalDu": 145,
        "resteAPayer": 53.5,
        "commentaire": "SMS le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "aurore.demachy@hotmail.fr"
      },
      {
        "nom": "MARCOTTE",
        "prenom": "DYLAN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 134.5,
        "totalDu": 145,
        "resteAPayer": 10.5,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dylan.marcotte27@gmail.com"
      },
      {
        "nom": "SAKPONOU",
        "prenom": "CONSTANT",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "consty1999@yahoo.fr"
      },
      {
        "nom": "RAY",
        "prenom": "GUILLAUME",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "guillaumeray13@gmail.com"
      },
      {
        "nom": "LECONTE",
        "prenom": "CYRIL",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "cyril.leconte80000@gmail.com"
      },
      {
        "nom": "DERCOURT",
        "prenom": "PHILIPPE",
        "college": 2,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [
          "SUP COL2"
        ],
        "email": "philippedercourt@orange.fr"
      },
      {
        "nom": "DOGMONT",
        "prenom": "MARIO",
        "college": 1,
        "modePaiement": "Chèque",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "dogmontmario@gmail.com"
      },
      {
        "nom": "BEAUCOURT",
        "prenom": "HERVE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "herve.beaucourt@orange.fr"
      },
      {
        "nom": "TEIXEIRA",
        "prenom": "OLIVIER",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2023-09-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 145,
        "totalDu": 145,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "olivier.teixeira@valeo.com"
      },
      {
        "nom": "SAUVE",
        "prenom": "JEREMIE",
        "college": "",
        "modePaiement": "Virement",
        "dateEntree": "2025-06-26",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0
        ],
        "totalRecu": 64,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "jeremie.sauve@hotmail.fr"
      },
      {
        "nom": "PORET",
        "prenom": "AURELIEN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2023-08-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "TEMPO",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0
        ],
        "totalRecu": 120,
        "totalDu": 145,
        "resteAPayer": 25,
        "commentaire": "Virement à faire le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "aureliennn@hotmail.fr"
      },
      {
        "nom": "MOREL",
        "prenom": "FRANCOIS",
        "college": 1,
        "modePaiement": "Paypall",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 145,
        "resteAPayer": 145,
        "commentaire": "Mail le 13/01/2025",
        "postesFO": [],
        "postesCSE": [],
        "email": "francois.morel710@gmail.com"
      },
      {
        "nom": "PORTAUX",
        "prenom": "REMY",
        "college": 3,
        "modePaiement": "Virement",
        "dateEntree": "Avant 2023",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        "totalRecu": 138,
        "totalDu": 145,
        "resteAPayer": 7,
        "commentaire": "// Gwen",
        "postesFO": [],
        "postesCSE": [],
        "email": "remy.portaux@valeo.com"
      },
      {
        "nom": "ROUILLARD",
        "prenom": "CHRISTOPHE",
        "college": 2,
        "modePaiement": "Virement",
        "dateEntree": "2023-01-15",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "super.marseillais@live.fr"
      },
      {
        "nom": "MERVILLE",
        "prenom": "MATHIEU",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2026-04-01",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "merville.matthieu@orange.fr"
      },
      {
        "nom": "JAMMES",
        "prenom": "CORENTIN",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2026-04-04",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "corentin.jammes@valeo.com"
      },
      {
        "nom": "LEMOINE",
        "prenom": "ISABELLE",
        "college": 1,
        "modePaiement": "Virement",
        "dateEntree": "2026-04-04",
        "dateSortie": "",
        "actif": true,
        "listeDiffusion": "OUI",
        "mois": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "totalRecu": 0,
        "totalDu": 0,
        "resteAPayer": 0,
        "commentaire": "",
        "postesFO": [],
        "postesCSE": [],
        "email": "lemoineisabelle@yahoo.fr"
      }
    ]
  },
  "bilans": {
    "2025": {
      "soldeDebut": 2512.78,
      "cotisationsRecues": 6551,
      "remboursementsTribunaux": 2500,
      "totalCredits": 9051,
      "cotisationsFed": 4531.84,
      "cotisationsUD": 3124.8,
      "cartes": 477.04,
      "timbres": 4054.8,
      "fraisTribunaux": 2000,
      "fraisGestion": 988.05,
      "fraisPropagande": 429.49,
      "fraisRepasAG": 297.82,
      "fraisGestionAdmin": 7.14,
      "fraisFonctionnement": 93.83,
      "totalDebits": 10644.69,
      "soldeFin": 919.09
    },
    "2026": {
      "soldeDebut": 2512.78,
      "cotisationsRecues": 6551,
      "remboursementsTribunaux": 2500,
      "totalCredits": 9051,
      "cotisationsFed": 2935.17,
      "cotisationsUD": 2037,
      "cartes": 291.92,
      "timbres": 2643.25,
      "fraisTribunaux": 2000,
      "fraisGestion": 988.05,
      "fraisPropagande": 429.49,
      "fraisRepasAG": 297.82,
      "fraisGestionAdmin": 7.14,
      "fraisFonctionnement": 93.83,
      "totalDebits": 7960.22,
      "soldeFin": 3603.56
    }
  }
};
